---
title: "`r params$team_name`"
output: html_document
params:
  team_name: "Expertise Support Team"
  team_key: "sup"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

# {.tabset}

## Projects

```{r}
source("functions.R")

# params = list(
#   team_name = "Expertise Support Team",
#   team_key  = "sup")

area_levels <- get_area_levels()
projects <- read_csv(projects_csv) %>% 
  filter(team_key == params$team_key) %>% 
  left_join(
    read_csv(teams_csv) %>% 
      select(team_key, team_htm),
    by = "team_key") %>% 
  mutate(
    Submitted = as_datetime(
      Timestamp, 
      format = "%m/%d/%Y %H:%M:%S", tz="America/Los_Angeles"),
    Project = glue("<a href={project_htm}>{`Project Title`}</a>"),
    area_name = factor(area_name, area_levels, ordered = T)) %>% 
  select(Area = area_name, Project, Submitted) %>% 
  arrange(Area, Project)

datatable(
  projects, 
  escape = F,
  plugins = 'natural', options = list(
    #dom = 't',
    columnDefs = list(list(
      type = 'natural', targets = "_all")))) %>% 
    formatDate("Submitted", method = "toLocaleString")
```

## People

```{r, results='asis'}
people <- read_csv(people_csv) %>% 
  filter(team_key == params$team_key)

people %>% 
  select(Group = role, Name = name, Email = email) %>% 
  datatable()
```

## Representation

```{r, results='asis'}
source("functions.R")

team <- read_csv(teams_csv) %>% 
  filter(team_key == params$team_key)

team %>% 
  select(starts_with("n_")) %>% 
  pivot_longer(everything(), names_to = "Group", values_to="Count") %>% 
  mutate(
    Group = str_replace(Group, "n_","")) %>% 
  kable()
```


