---
title: "AIA Charrette 2020 for Santa Barbara"
subtitle: "_re invigorate, re invent, re imagine, re purpose_"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

Please [Submit](./submit.html) your own project proposal and the website will be manually regenerated (~ next day) and populated with it here.

## Map

```{r}
source("functions.R")

area_plys <- get_area_plys()

# table(area_plys$layer, useNA = "ifany")

# setdiff(
#   sort(unique(area_plys$layer)), 
#   c("Main Focus Areas", "Additional Focus Areas")) %>% 
#   paste(collapse ='", "') %>% cat()

bb <- area_plys %>% 
  filter(layer %in% c("Main Focus Areas", "Additional Focus Areas")) %>% 
  st_bbox()

main_areas <- area_plys %>% 
      filter(layer == "Main Focus Areas")
add_areas <- area_plys %>% 
      filter(layer == "Additional Focus Areas")
main_labels <- main_areas$label_html
add_labels  <- add_areas$label_html

leaflet( width = "100%") %>% 
  addProviderTiles(providers$Stamen.TonerLite, group = "Black & white",
    options = providerTileOptions(opacity = 0.5)) %>% 
  addProviderTiles(
    providers$CartoDB.Voyager, group = "Streets",
    options = providerTileOptions(opacity = 0.8)) %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite",
    options = providerTileOptions(opacity = 0.5)) %>% 
  addPolygons(
    data = main_areas,
    group = "Main Focus Areas",
    color     = ~color, opacity     = 0.9, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.6,
    label = lapply(main_labels, HTML), popup = ~popup_html) %>%
  addPolygons(
    data = add_areas,
    group = "Additional Focus Areas",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3,
    label = lapply(add_labels, HTML), popup = ~popup_html) %>%
  addPolygons(
    data = area_plys %>% 
      filter(layer == "AUD_Priority"),
    group = "AUD_Priority",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3) %>%
  addPolygons(
    data = area_plys %>% 
      filter(layer == "Central Business District"),
    group = "Central Business District",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3) %>%
  addPolygons(
    data = area_plys %>% 
      filter(layer == "Downtown area for clipping polygons"),
    group = "Downtown area for clipping polygons",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3) %>%
  addPolygons(
    data = area_plys %>% 
      filter(layer == "Historic District (El Pueblo Viejo)"),
    group = "Historic District (El Pueblo Viejo)",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3) %>%
  addPolygons(
    data = area_plys %>% 
      filter(layer == "Zoning"),
    group = "Zoning",
    color     = ~color, opacity     = 0.6, weight = 0.5,
    fillColor = ~color, fillOpacity = 0.3) %>%
  addLayersControl(
    baseGroups = c("Black & white", "Streets", "Satellite"),
    overlayGroups = c(
      "Main Focus Areas", "Additional Focus Areas",
      "AUD_Priority", "Central Business District", 
      "Downtown area for clipping polygons", 
      "Historic District (El Pueblo Viejo)", "Zoning"),
    options = layersControlOptions(collapsed = T)) %>% 
  hideGroup("AUD_Priority") %>% 
  hideGroup("Central Business District") %>% 
  hideGroup("Downtown area for clipping polygons") %>% 
  hideGroup("Historic District (El Pueblo Viejo)") %>% 
  hideGroup("Zoning") %>% 
  fitBounds(bb[['xmin']], bb[['ymin']], bb[['xmax']], bb[['ymax']])
```

## Projects

```{r}
area_levels <- get_area_levels()
projects <- read_csv(projects_csv) %>% 
  left_join(
    read_csv(teams_csv) %>% 
      select(team_key, team_htm),
    by = "team_key") %>% 
  mutate(
    Submitted = as_datetime(
      Timestamp, 
      format = "%m/%d/%Y %H:%M:%S", tz="America/Los_Angeles"),
    Project   = glue("<a href={project_htm}>{`Project Title`}</a>"), 
    Team      = glue("<a href={team_htm}>{team_name}</a>"),
    area_name = factor(area_name, area_levels, ordered = T)) %>% 
  select(Area = area_name, Project, Team, Submitted) %>% 
  arrange(Area, Project)

datatable(
  projects, 
  escape = F,
  plugins = 'natural', options = list(
    #dom = 't',
    columnDefs = list(list(
      type = 'natural', targets = "_all")))) %>% 
    formatDate("Submitted", method = "toLocaleString")
    # method = "toLocaleString",
    # params = list("se", list(timeZone = "America/Los_Angeles")))

```
